### PR TITLE
chore: update github workflows

### PR DESCRIPTION
**Pull request by nepalevov**

### CODE REVIEW

**Comment by Allob** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/458558)

**Comment by taa-epam** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/462427)

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-analytics-realtime-pr-42.nightly-test.deltixhub.io
>E2E tests status:

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-analytics-realtime-pr-42.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by Allob** [comment]
Fixed within #50 , but without bunch of updates for python libraries.

**Pull request closed without merging**
